# helm repo add rancher-stable https://releases.rancher.com/server-charts/stable

# helm install rancher rancher-stable/rancher -f rancher-values.yaml --namespace cattle-system --create-namespace


hostname: rancher.jelmerklaveren.nl
replicas: 1

ingress:
  tls:
    source: secret 

tls: external

