persistence:
  config:
    enabled: true
    mountPath: /app/data
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: "longhorn" # Bijv. 'longhorn' of 'nfs'


ingress:
  main:
    enabled: true
    hosts:
      - host: homarr.jelmerklaveren.nl
        paths:
          - path: /
